---

# A list of users that should be given rights with SSH. Only groups is optional.
ssh_users:
  - name: sarah
    password: "{{ vault_sarah_password }}"
    groups: sudo,wpc,www-data

ssh_user_keys:
  - name: sarah
    ssh_key: https://github.com/sarah-savage.keys

sites:
  - site_name: wpc.wpconcierge.org
    server_name: wpc.wpconcierge.org
    server_alias:
    doc_root: /var/www/wpc.wpconcierge.org

certbot_create_if_missing: true
certbot_certs:
  - email: sarah@wpconcierge.com
    domains:
      - wpc.wpconcierge.org

mysql_databases:
  - name: wpconcierge

mysql_users:
  - name: wpconcierge
    host: '%'
    password: "{{ wpconcierge_mysql_password }}"
    priv: wpconcierge.*:ALL
    state: present

wordpress_sites:
  - site_name: "WPConcierge Test Site"
    site_url: wpc.wpconcierge.org
    doc_root: /var/www/wpc.wpconcierge.org
    db_name: wpconcierge
    db_user: wpconcierge
    db_password: "{{ wpconcierge_mysql_password }}"
    admin_user: Sarah
    admin_password: "{{ wpconcierge_admin_password }}"
    admin_email: sarah@wpconcierge.org