---
- name: Check for WordPress existing
  find:
    path: "{{ item.doc_root }}"
  loop: "{{ sites }}"
  register: files_exist

- name: Install WordPress
  command: "wp core download --path={{ item.item.doc_root}}"
  loop: "{{ files_exist.results }}"
  when: item.matched == 0
  become: yes
  become_user: sarah