---
- name: Check for WordPress existing
  find:
    path: "{{ item.doc_root }}"
  loop: "{{ wordpress_sites }}"
  register: files_exist

- name: Install WordPress
  include_tasks: install.yml
  loop: "{{ files_exist.results }}"
  when: item.matched == 0